"""create documents table

Revision ID: 83984658475d
Revises: aef6edc660b2
Create Date: 2026-07-21 16:26:35.871155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83984658475d'
down_revision: Union[str, Sequence[str], None] = 'aef6edc660b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_endpoint_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=30), server_default='rss', nullable=False),
    sa.Column('external_id', sa.String(length=2048), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('title_original', sa.Text(), nullable=False),
    sa.Column('summary_original', sa.Text(), nullable=True),
    sa.Column('content_original', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_endpoint_id'], ['source_endpoints.id'], name=op.f('fk_documents_source_endpoint_id_source_endpoints'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('source_endpoint_id', 'external_id', name='uq_documents_endpoint_external_id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_country'), 'documents', ['country'], unique=False)
    op.create_index('ix_documents_endpoint_published_at', 'documents', ['source_endpoint_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_documents_language'), 'documents', ['language'], unique=False)
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_documents_retrieved_at'), 'documents', ['retrieved_at'], unique=False)
    op.create_index(op.f('ix_documents_source_endpoint_id'), 'documents', ['source_endpoint_id'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index('ix_documents_source_published_at', 'documents', ['source_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_documents_source_type'), 'documents', ['source_type'], unique=False)
    op.create_index('ix_documents_source_type_published_at', 'documents', ['source_type', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_source_type_published_at', table_name='documents')
    op.drop_index(op.f('ix_documents_source_type'), table_name='documents')
    op.drop_index('ix_documents_source_published_at', table_name='documents')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_endpoint_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_retrieved_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_language'), table_name='documents')
    op.drop_index('ix_documents_endpoint_published_at', table_name='documents')
    op.drop_index(op.f('ix_documents_country'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
