"""create source endpoints table

Revision ID: aef6edc660b2
Revises: 0d0ec5dd17a1
Create Date: 2026-07-21 16:05:10.399905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aef6edc660b2'
down_revision: Union[str, Sequence[str], None] = '0d0ec5dd17a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_endpoints',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('endpoint_type', sa.String(length=30), server_default='rss', nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), server_default='900', nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.String(length=512), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('poll_interval_seconds >= 60', name=op.f('ck_source_endpoints_poll_interval_minimum')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_endpoints_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_endpoints')),
    sa.UniqueConstraint('url', name='uq_source_endpoints_url')
    )
    op.create_index('ix_source_endpoints_due_poll', 'source_endpoints', ['status', 'next_poll_at'], unique=False)
    op.create_index(op.f('ix_source_endpoints_endpoint_type'), 'source_endpoints', ['endpoint_type'], unique=False)
    op.create_index(op.f('ix_source_endpoints_source_id'), 'source_endpoints', ['source_id'], unique=False)
    op.create_index('ix_source_endpoints_source_status', 'source_endpoints', ['source_id', 'status'], unique=False)
    op.create_index(op.f('ix_source_endpoints_status'), 'source_endpoints', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_endpoints_status'), table_name='source_endpoints')
    op.drop_index('ix_source_endpoints_source_status', table_name='source_endpoints')
    op.drop_index(op.f('ix_source_endpoints_source_id'), table_name='source_endpoints')
    op.drop_index(op.f('ix_source_endpoints_endpoint_type'), table_name='source_endpoints')
    op.drop_index('ix_source_endpoints_due_poll', table_name='source_endpoints')
    op.drop_table('source_endpoints')
    # ### end Alembic commands ###
