"""site authentication authority foundation

Revision ID: b8d0f2a4c6e8
Revises: a7c9e1f3b5d4
Create Date: 2026-08-25 22:46:33.245099

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8d0f2a4c6e8"
down_revision: str | Sequence[str] | None = "a7c9e1f3b5d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_roles",
        sa.Column("slug", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("authority_rank", sa.Integer(), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_auth_roles_name_nonempty")),
        sa.CheckConstraint(
            "jsonb_typeof(capabilities) = 'array'", name=op.f("ck_auth_roles_capabilities_array")
        ),
        sa.CheckConstraint("slug IN ('owner', 'admin', 'user')", name=op.f("ck_auth_roles_slug")),
        sa.CheckConstraint(
            "authority_rank BETWEEN 0 AND 1000", name=op.f("ck_auth_roles_authority_rank")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_auth_roles")),
    )
    op.create_table(
        "auth_users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_handle", sa.LargeBinary(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(display_name) <> ''", name=op.f("ck_auth_users_display_name_nonempty")
        ),
        sa.CheckConstraint("btrim(username) <> ''", name=op.f("ck_auth_users_username_nonempty")),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'disabled')", name=op.f("ck_auth_users_status")
        ),
        sa.CheckConstraint(
            "username = lower(username)", name=op.f("ck_auth_users_username_canonical")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_users")),
        sa.UniqueConstraint("public_id", name=op.f("uq_auth_users_public_id")),
        sa.UniqueConstraint("user_handle", name=op.f("uq_auth_users_user_handle")),
        sa.UniqueConstraint("username", name="uq_auth_users_username"),
    )
    op.create_table(
        "auth_enrollment_tokens",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("issued_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "btrim(reason) <> ''", name=op.f("ck_auth_enrollment_tokens_reason_nonempty")
        ),
        sa.CheckConstraint(
            "purpose IN ('bootstrap', 'invitation', 'recovery', 'passkey_addition')",
            name=op.f("ck_auth_enrollment_tokens_purpose"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_auth_enrollment_tokens_expiry_after_creation")
        ),
        sa.CheckConstraint(
            "length(token_digest) = 64", name=op.f("ck_auth_enrollment_tokens_token_digest_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_enrollment_tokens_issued_by_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_enrollment_tokens_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_enrollment_tokens")),
        sa.UniqueConstraint("token_digest", name="uq_auth_enrollment_tokens_token_digest"),
    )
    op.create_index(
        "ix_auth_enrollment_tokens_user_expiry",
        "auth_enrollment_tokens",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "auth_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("session_public_id", sa.UUID(), nullable=True),
        sa.Column("credential_public_id", sa.UUID(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(reason_code) <> ''", name=op.f("ck_auth_events_reason_code_nonempty")
        ),
        sa.CheckConstraint(
            "event_type IN ('owner_bootstrap_started', 'user_invited', 'passkey_registered', 'passkey_authenticated', 'passkey_revoked', 'login_failed', 'logout', 'session_revoked', 'recovery_codes_generated', 'recovery_code_consumed', 'recovery_failed', 'role_assigned', 'role_revoked', 'user_enabled', 'user_disabled', 'authorization_denied', 'csrf_rejected')",
            name=op.f("ck_auth_events_event_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(details) = 'object'", name=op.f("ck_auth_events_details_object")
        ),
        sa.CheckConstraint(
            "outcome IN ('succeeded', 'failed', 'denied')", name=op.f("ck_auth_events_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_events_actor_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_events_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_events")),
    )
    op.create_index(
        "ix_auth_events_user_recorded", "auth_events", ["user_id", "recorded_at"], unique=False
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("csrf_digest", sa.String(length=64), nullable=False),
        sa.Column("credential_public_id", sa.UUID(), nullable=False),
        sa.Column("user_agent_digest", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND btrim(revocation_reason) <> '')",
            name=op.f("ck_auth_sessions_revocation_complete"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_auth_sessions_expiry_after_creation")
        ),
        sa.CheckConstraint(
            "length(csrf_digest) = 64", name=op.f("ck_auth_sessions_csrf_digest_sha256")
        ),
        sa.CheckConstraint(
            "length(token_digest) = 64", name=op.f("ck_auth_sessions_token_digest_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_sessions_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("public_id", name=op.f("uq_auth_sessions_public_id")),
        sa.UniqueConstraint("token_digest", name="uq_auth_sessions_token_digest"),
    )
    op.create_index(
        "ix_auth_sessions_user_expiry", "auth_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "auth_user_roles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_slug", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("assigned_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.CheckConstraint("btrim(reason) <> ''", name=op.f("ck_auth_user_roles_reason_nonempty")),
        sa.CheckConstraint(
            "status IN ('active', 'revoked')", name=op.f("ck_auth_user_roles_status")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_user_roles_assigned_by_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_user_roles_revoked_by_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_slug"],
            ["auth_roles.slug"],
            name=op.f("fk_auth_user_roles_role_slug_auth_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_user_roles_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_user_roles")),
    )
    op.create_index(
        "uq_auth_user_roles_active",
        "auth_user_roles",
        ["user_id", "role_slug"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "auth_webauthn_ceremonies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ceremony_type", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("challenge", sa.LargeBinary(), nullable=False),
        sa.Column("binding_token_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ceremony_type IN ('registration', 'authentication')",
            name=op.f("ck_auth_webauthn_ceremonies_type"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at",
            name=op.f("ck_auth_webauthn_ceremonies_expiry_after_creation"),
        ),
        sa.CheckConstraint(
            "length(binding_token_digest) = 64",
            name=op.f("ck_auth_webauthn_ceremonies_binding_digest_sha256"),
        ),
        sa.CheckConstraint(
            "length(challenge) BETWEEN 32 AND 128",
            name=op.f("ck_auth_webauthn_ceremonies_challenge_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_webauthn_ceremonies_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_webauthn_ceremonies")),
    )
    op.create_index(
        "ix_auth_webauthn_ceremonies_expiry",
        "auth_webauthn_ceremonies",
        ["expires_at", "used_at"],
        unique=False,
    )
    op.create_table(
        "auth_webauthn_credentials",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("credential_public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("aaguid", sa.String(length=36), nullable=True),
        sa.Column(
            "transports",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("device_type", sa.String(length=30), nullable=False),
        sa.Column("backed_up", sa.Boolean(), nullable=False),
        sa.Column(
            "user_verification_required",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "cred_protect_requested", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("cred_protect_confirmed", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(status = 'active' AND revoked_at IS NULL AND revocation_reason IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL AND btrim(revocation_reason) <> '')",
            name=op.f("ck_auth_webauthn_credentials_revocation_complete"),
        ),
        sa.CheckConstraint(
            "btrim(label) <> ''", name=op.f("ck_auth_webauthn_credentials_label_nonempty")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(transports) = 'array'",
            name=op.f("ck_auth_webauthn_credentials_transports_array"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked')", name=op.f("ck_auth_webauthn_credentials_status")
        ),
        sa.CheckConstraint(
            "sign_count >= 0", name=op.f("ck_auth_webauthn_credentials_sign_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_webauthn_credentials_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_webauthn_credentials")),
        sa.UniqueConstraint("credential_id", name="uq_auth_webauthn_credentials_credential_id"),
        sa.UniqueConstraint("public_id", name=op.f("uq_auth_webauthn_credentials_public_id")),
    )
    op.create_index(
        "ix_auth_webauthn_credentials_user_active",
        "auth_webauthn_credentials",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "auth_recovery_codes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("batch_public_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("code_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_for_enrollment_token_id", sa.BigInteger(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(used_at IS NULL AND used_for_enrollment_token_id IS NULL) OR (used_at IS NOT NULL AND used_for_enrollment_token_id IS NOT NULL)",
            name=op.f("ck_auth_recovery_codes_consumption_complete"),
        ),
        sa.CheckConstraint(
            "length(code_digest) = 64", name=op.f("ck_auth_recovery_codes_code_digest_sha256")
        ),
        sa.CheckConstraint(
            "ordinal BETWEEN 1 AND 100", name=op.f("ck_auth_recovery_codes_ordinal")
        ),
        sa.ForeignKeyConstraint(
            ["used_for_enrollment_token_id"],
            ["auth_enrollment_tokens.id"],
            name=op.f("fk_auth_recovery_codes_used_for_enrollment_token_id_auth_enrollment_tokens"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
            name=op.f("fk_auth_recovery_codes_user_id_auth_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_recovery_codes")),
        sa.UniqueConstraint("code_digest", name="uq_auth_recovery_codes_code_digest"),
    )
    op.create_index(
        "ix_auth_recovery_codes_user_batch",
        "auth_recovery_codes",
        ["user_id", "batch_public_id"],
        unique=False,
    )
    op.execute("""
        INSERT INTO auth_roles (slug, name, authority_rank, capabilities) VALUES
          ('owner', 'Owner', 1000, '["site.read", "site.operate", "site.admin", "owner.policy"]'::jsonb),
          ('admin', 'Administrator', 500, '["site.read", "site.operate", "site.admin"]'::jsonb),
          ('user', 'User', 100, '["site.read"]'::jsonb)
    """)
    op.execute("""
        CREATE FUNCTION auth_enforce_six_active_passkeys() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.status = 'active' AND (
            SELECT count(*) FROM auth_webauthn_credentials
             WHERE user_id = NEW.user_id AND status = 'active'
               AND id IS DISTINCT FROM NEW.id
          ) >= 6 THEN
            RAISE EXCEPTION 'an account may have at most six active passkeys';
          END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER trg_auth_six_active_passkeys
          BEFORE INSERT OR UPDATE OF user_id, status ON auth_webauthn_credentials
          FOR EACH ROW EXECUTE FUNCTION auth_enforce_six_active_passkeys();
    """)
    op.execute("""
        CREATE FUNCTION auth_events_are_immutable() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'auth events are append-only';
        END $$;
        CREATE TRIGGER trg_auth_events_immutable
          BEFORE UPDATE OR DELETE ON auth_events
          FOR EACH ROW EXECUTE FUNCTION auth_events_are_immutable();
    """)
    op.execute("""
        CREATE FUNCTION auth_preserve_last_owner() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF OLD.role_slug = 'owner' AND OLD.status = 'active'
             AND (TG_OP = 'DELETE' OR NEW.status <> 'active')
             AND (SELECT count(*) FROM auth_user_roles r JOIN auth_users u ON u.id = r.user_id
                   WHERE r.role_slug = 'owner' AND r.status = 'active'
                     AND u.status = 'active' AND r.id <> OLD.id) = 0 THEN
            RAISE EXCEPTION 'the final active Owner authority cannot be removed';
          END IF;
          RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END $$;
        CREATE TRIGGER trg_auth_preserve_last_owner
          BEFORE UPDATE OF status OR DELETE ON auth_user_roles
          FOR EACH ROW EXECUTE FUNCTION auth_preserve_last_owner();
    """)
    op.execute("""
        CREATE FUNCTION auth_preserve_last_owner_user() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF OLD.status = 'active' AND (TG_OP = 'DELETE' OR NEW.status <> 'active')
             AND EXISTS (SELECT 1 FROM auth_user_roles WHERE user_id = OLD.id
                         AND role_slug = 'owner' AND status = 'active')
             AND (SELECT count(*) FROM auth_user_roles r JOIN auth_users u ON u.id = r.user_id
                   WHERE r.role_slug = 'owner' AND r.status = 'active'
                     AND u.status = 'active' AND u.id <> OLD.id) = 0 THEN
            RAISE EXCEPTION 'the final active Owner identity cannot be disabled or removed';
          END IF;
          RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END $$;
        CREATE TRIGGER trg_auth_preserve_last_owner_user
          BEFORE UPDATE OF status OR DELETE ON auth_users
          FOR EACH ROW EXECUTE FUNCTION auth_preserve_last_owner_user();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    if connection.execute(sa.text("SELECT EXISTS (SELECT 1 FROM auth_users)")).scalar():
        raise RuntimeError("Refusing to remove authentication tables while identities exist.")
    op.execute("DROP TRIGGER trg_auth_events_immutable ON auth_events")
    op.execute("DROP FUNCTION auth_events_are_immutable()")
    op.execute("DROP TRIGGER trg_auth_six_active_passkeys ON auth_webauthn_credentials")
    op.execute("DROP FUNCTION auth_enforce_six_active_passkeys()")
    op.execute("DROP TRIGGER trg_auth_preserve_last_owner ON auth_user_roles")
    op.execute("DROP FUNCTION auth_preserve_last_owner()")
    op.execute("DROP TRIGGER IF EXISTS trg_auth_preserve_last_owner_user ON auth_users")
    op.execute("DROP FUNCTION IF EXISTS auth_preserve_last_owner_user()")
    op.drop_index("ix_auth_recovery_codes_user_batch", table_name="auth_recovery_codes")
    op.drop_table("auth_recovery_codes")
    op.drop_index(
        "ix_auth_webauthn_credentials_user_active",
        table_name="auth_webauthn_credentials",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("auth_webauthn_credentials")
    op.drop_index("ix_auth_webauthn_ceremonies_expiry", table_name="auth_webauthn_ceremonies")
    op.drop_table("auth_webauthn_ceremonies")
    op.drop_index(
        "uq_auth_user_roles_active",
        table_name="auth_user_roles",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("auth_user_roles")
    op.drop_index("ix_auth_sessions_user_expiry", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_auth_events_user_recorded", table_name="auth_events")
    op.drop_table("auth_events")
    op.drop_index("ix_auth_enrollment_tokens_user_expiry", table_name="auth_enrollment_tokens")
    op.drop_table("auth_enrollment_tokens")
    op.drop_table("auth_users")
    op.drop_table("auth_roles")
    # ### end Alembic commands ###
