"""create ingestion runs table

Revision ID: b9e26ebfcb4a
Revises: c8e7eb47b772
Create Date: 2026-07-21 19:14:40.607154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9e26ebfcb4a'
down_revision: Union[str, Sequence[str], None] = 'c8e7eb47b772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_endpoint_id', sa.BigInteger(), nullable=True),
    sa.Column('endpoint_url', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), server_default='scheduled', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_bytes', sa.BigInteger(), nullable=True),
    sa.Column('items_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_unchanged', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            http_status IS NULL\n            OR (http_status >= 100 AND http_status <= 599)\n            ', name=op.f('ck_ingestion_runs_http_status_valid')),
    sa.CheckConstraint('\n            items_seen >= 0\n            AND items_created >= 0\n            AND items_updated >= 0\n            AND items_unchanged >= 0\n            AND items_failed >= 0\n            ', name=op.f('ck_ingestion_runs_item_counts_nonnegative')),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name=op.f('ck_ingestion_runs_duration_nonnegative')),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name=op.f('ck_ingestion_runs_finished_after_started')),
    sa.CheckConstraint('response_bytes IS NULL OR response_bytes >= 0', name=op.f('ck_ingestion_runs_response_bytes_nonnegative')),
    sa.ForeignKeyConstraint(['source_endpoint_id'], ['source_endpoints.id'], name=op.f('fk_ingestion_runs_source_endpoint_id_source_endpoints'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ingestion_runs_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index('ix_ingestion_runs_endpoint_started_at', 'ingestion_runs', ['source_endpoint_id', 'started_at'], unique=False)
    op.create_index('ix_ingestion_runs_source_started_at', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_index('ix_ingestion_runs_status_started_at', 'ingestion_runs', ['status', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_runs_status_started_at', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_source_started_at', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_endpoint_started_at', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
