"""Install the Phase 3 acquisition-control persistence foundation.

Revision ID: e4f6a8b0c213
Revises: d1b3e5f7a902
Create Date: 2026-07-31

Create exact adapter/configuration registries, durable acquisition leases,
global secret references with acquisition bindings, and PostgreSQL-authoritative
hierarchical rate policy/state. Existing endpoints are deliberately not
backfilled or activated.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e4f6a8b0c213"
down_revision: str | Sequence[str] | None = "d1b3e5f7a902"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acquisition_adapters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("implementation", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="candidate", nullable=False),
        sa.Column(
            "configuration_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(implementation) <> ''",
            name=op.f("ck_acquisition_adapters_implementation_nonempty"),
        ),
        sa.CheckConstraint("btrim(slug) <> ''", name=op.f("ck_acquisition_adapters_slug_nonempty")),
        sa.CheckConstraint(
            "btrim(version) <> ''", name=op.f("ck_acquisition_adapters_version_nonempty")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(configuration_schema) = 'object' AND jsonb_typeof(provenance) = 'object'",
            name=op.f("ck_acquisition_adapters_json_objects"),
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'active', 'retired', 'blocked')",
            name=op.f("ck_acquisition_adapters_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_adapters")),
        sa.UniqueConstraint("public_id", name=op.f("uq_acquisition_adapters_public_id")),
        sa.UniqueConstraint("slug", "version", name="uq_acquisition_adapters_slug_version"),
    )
    op.create_index(
        "uq_acquisition_adapters_active_slug",
        "acquisition_adapters",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "acquisition_rate_limit_policies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("requests_per_period", sa.Integer(), server_default="6", nullable=False),
        sa.Column("period_seconds", sa.Integer(), server_default="60", nullable=False),
        sa.Column("burst_size", sa.Integer(), server_default="1", nullable=False),
        sa.Column("max_concurrency", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "minimum_request_spacing_seconds", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("poll_interval_seconds", sa.Integer(), server_default="900", nullable=False),
        sa.Column("daily_request_budget", sa.Integer(), nullable=True),
        sa.Column("retry_base_seconds", sa.Integer(), server_default="60", nullable=False),
        sa.Column("retry_max_seconds", sa.Integer(), server_default="86400", nullable=False),
        sa.Column("retry_jitter_percent", sa.Integer(), server_default="20", nullable=False),
        sa.Column(
            "exhaustion_action", sa.String(length=30), server_default="delay", nullable=False
        ),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(actor) <> '' AND btrim(reason) <> ''",
            name=op.f("ck_acquisition_rate_limit_policies_audit_nonempty"),
        ),
        sa.CheckConstraint(
            "exhaustion_action IN ('delay', 'disable', 'operational_exception')",
            name=op.f("ck_acquisition_rate_limit_policies_exhaustion_action"),
        ),
        sa.CheckConstraint(
            "mode IN ('provider_defined', 'robots_aware', 'conservative', 'custom')",
            name=op.f("ck_acquisition_rate_limit_policies_mode"),
        ),
        sa.CheckConstraint(
            "burst_size BETWEEN 1 AND 100", name=op.f("ck_acquisition_rate_limit_policies_burst")
        ),
        sa.CheckConstraint(
            "daily_request_budget IS NULL OR daily_request_budget > 0",
            name=op.f("ck_acquisition_rate_limit_policies_daily_budget"),
        ),
        sa.CheckConstraint(
            "max_concurrency BETWEEN 1 AND 16",
            name=op.f("ck_acquisition_rate_limit_policies_concurrency"),
        ),
        sa.CheckConstraint(
            "minimum_request_spacing_seconds >= 0",
            name=op.f("ck_acquisition_rate_limit_policies_spacing_nonnegative"),
        ),
        sa.CheckConstraint(
            "period_seconds BETWEEN 1 AND 86400",
            name=op.f("ck_acquisition_rate_limit_policies_period"),
        ),
        sa.CheckConstraint(
            "poll_interval_seconds >= 60",
            name=op.f("ck_acquisition_rate_limit_policies_poll_interval"),
        ),
        sa.CheckConstraint(
            "requests_per_period BETWEEN 1 AND 10000",
            name=op.f("ck_acquisition_rate_limit_policies_requests"),
        ),
        sa.CheckConstraint(
            "retry_base_seconds BETWEEN 1 AND 86400",
            name=op.f("ck_acquisition_rate_limit_policies_retry_base"),
        ),
        sa.CheckConstraint(
            "retry_jitter_percent BETWEEN 0 AND 50",
            name=op.f("ck_acquisition_rate_limit_policies_retry_jitter"),
        ),
        sa.CheckConstraint(
            "retry_max_seconds BETWEEN retry_base_seconds AND 604800",
            name=op.f("ck_acquisition_rate_limit_policies_retry_max"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_rate_limit_policies")),
        sa.UniqueConstraint("public_id", name=op.f("uq_acquisition_rate_limit_policies_public_id")),
        sa.UniqueConstraint(
            "slug", "version", name="uq_acquisition_rate_limit_policies_slug_version"
        ),
    )
    op.create_table(
        "secret_references",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("identity", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("backend", sa.String(length=50), nullable=False),
        sa.Column("backend_reference", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=30), server_default="configured", nullable=False),
        sa.Column("rotation_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_resolution_status", sa.String(length=30), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "backend IN ('environment', 'systemd_credential', 'external_secret_store')",
            name=op.f("ck_secret_references_backend"),
        ),
        sa.CheckConstraint(
            "btrim(actor) <> '' AND btrim(reason) <> ''",
            name=op.f("ck_secret_references_audit_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(identity) <> '' AND btrim(display_name) <> '' AND btrim(backend_reference) <> ''",
            name=op.f("ck_secret_references_identity_nonempty"),
        ),
        sa.CheckConstraint(
            "last_resolution_status IS NULL OR last_resolution_status IN ('resolved', 'missing', 'invalid', 'unavailable', 'permission_denied')",
            name=op.f("ck_secret_references_resolution_status"),
        ),
        sa.CheckConstraint(
            "state IN ('configured', 'missing', 'invalid', 'expired', 'rotation_required', 'disabled')",
            name=op.f("ck_secret_references_state"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secret_references")),
        sa.UniqueConstraint("identity", name=op.f("uq_secret_references_identity")),
        sa.UniqueConstraint("public_id", name=op.f("uq_secret_references_public_id")),
    )
    op.create_table(
        "acquisition_adapter_artifact_capabilities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("adapter_id", sa.BigInteger(), nullable=False),
        sa.Column("artifact_format_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "identification_supported",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "safe_parser_supported", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "safe_extraction_supported",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "safe_extraction_supported = false OR safe_parser_supported",
            name=op.f("ck_acquisition_adapter_artifact_capabilities_extraction_requires_parser"),
        ),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["acquisition_adapters.id"],
            name=op.f(
                "fk_acquisition_adapter_artifact_capabilities_adapter_id_acquisition_adapters"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_format_id"],
            ["artifact_formats.id"],
            name=op.f(
                "fk_acquisition_adapter_artifact_capabilities_artifact_format_id_artifact_formats"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_adapter_artifact_capabilities")),
        sa.UniqueConstraint(
            "adapter_id",
            "artifact_format_id",
            name="uq_acquisition_adapter_artifact_capabilities_adapter_format",
        ),
    )
    op.create_table(
        "acquisition_adapter_compatibilities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("adapter_id", sa.BigInteger(), nullable=False),
        sa.Column("endpoint_type", sa.String(length=50), nullable=False),
        sa.Column("endpoint_format", sa.String(length=50), nullable=False),
        sa.Column("acquisition_method", sa.String(length=50), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=True),
        sa.Column("platform_key", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(platform_key = '*' AND platform IS NULL) OR (platform_key = platform AND platform IS NOT NULL)",
            name=op.f("ck_acquisition_adapter_compatibilities_platform_key"),
        ),
        sa.ForeignKeyConstraint(
            ["acquisition_method"],
            ["acquisition_methods.slug"],
            name=op.f(
                "fk_acquisition_adapter_compatibilities_acquisition_method_acquisition_methods"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["acquisition_adapters.id"],
            name=op.f("fk_acquisition_adapter_compatibilities_adapter_id_acquisition_adapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_format"],
            ["endpoint_formats.slug"],
            name=op.f("fk_acquisition_adapter_compatibilities_endpoint_format_endpoint_formats"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_type"],
            ["endpoint_types.slug"],
            name=op.f("fk_acquisition_adapter_compatibilities_endpoint_type_endpoint_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["platform"],
            ["platforms.slug"],
            name=op.f("fk_acquisition_adapter_compatibilities_platform_platforms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_adapter_compatibilities")),
        sa.UniqueConstraint(
            "adapter_id",
            "endpoint_type",
            "endpoint_format",
            "acquisition_method",
            "platform_key",
            name="uq_acquisition_adapter_compatibilities_exact_tuple",
        ),
    )
    op.create_table(
        "acquisition_adapter_secret_slots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("adapter_id", sa.BigInteger(), nullable=False),
        sa.Column("slot_name", sa.String(length=100), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("authentication_types", sa.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("permitted_scopes", sa.ARRAY(sa.String(length=30)), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "authentication_types <@ ARRAY['none', 'bearer_token', 'api_key_header', 'api_key_query', 'basic_auth', 'oauth2_client_credentials', 'cookie_session', 'ssh_key', 'custom']::varchar[]",
            name=op.f("ck_acquisition_adapter_secret_slots_auth_types"),
        ),
        sa.CheckConstraint(
            "btrim(slot_name) <> ''",
            name=op.f("ck_acquisition_adapter_secret_slots_slot_name_nonempty"),
        ),
        sa.CheckConstraint(
            "permitted_scopes <@ ARRAY['endpoint', 'source', 'platform_account', 'installation']::varchar[]",
            name=op.f("ck_acquisition_adapter_secret_slots_scopes"),
        ),
        sa.CheckConstraint(
            "cardinality(authentication_types) > 0",
            name=op.f("ck_acquisition_adapter_secret_slots_auth_types_nonempty"),
        ),
        sa.CheckConstraint(
            "cardinality(permitted_scopes) > 0",
            name=op.f("ck_acquisition_adapter_secret_slots_scopes_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["acquisition_adapters.id"],
            name=op.f("fk_acquisition_adapter_secret_slots_adapter_id_acquisition_adapters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_adapter_secret_slots")),
        sa.UniqueConstraint(
            "adapter_id", "slot_name", name="uq_acquisition_adapter_secret_slots_adapter_slot"
        ),
    )
    op.create_table(
        "acquisition_platform_accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("account_key", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(account_key) <> '' AND btrim(display_name) <> ''",
            name=op.f("ck_acquisition_platform_accounts_identity_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["platform"],
            ["platforms.slug"],
            name=op.f("fk_acquisition_platform_accounts_platform_platforms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_platform_accounts")),
        sa.UniqueConstraint(
            "platform", "account_key", name="uq_acquisition_platform_accounts_platform_key"
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_acquisition_platform_accounts_public_id")),
    )
    op.create_table(
        "secret_reference_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("secret_reference_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(actor) <> '' AND btrim(reason) <> ''",
            name=op.f("ck_secret_reference_events_audit_nonempty"),
        ),
        sa.CheckConstraint(
            "event_type IN ('created', 'state_changed', 'rotated', 'resolution_succeeded', 'resolution_failed', 'disabled')",
            name=op.f("ck_secret_reference_events_event_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(details) = 'object'",
            name=op.f("ck_secret_reference_events_details_object"),
        ),
        sa.ForeignKeyConstraint(
            ["secret_reference_id"],
            ["secret_references.id"],
            name=op.f("fk_secret_reference_events_secret_reference_id_secret_references"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secret_reference_events")),
    )
    op.create_index(
        "ix_secret_reference_events_reference_recorded",
        "secret_reference_events",
        ["secret_reference_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "acquisition_endpoint_configurations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("source_endpoint_id", sa.BigInteger(), nullable=False),
        sa.Column("adapter_id", sa.BigInteger(), nullable=False),
        sa.Column("configuration_version", sa.String(length=100), nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=30), server_default="candidate", nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(actor) <> '' AND btrim(reason) <> ''",
            name=op.f("ck_acquisition_endpoint_configurations_audit_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(configuration_version) <> ''",
            name=op.f("ck_acquisition_endpoint_configurations_version_nonempty"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(configuration) = 'object' AND jsonb_typeof(provenance) = 'object'",
            name=op.f("ck_acquisition_endpoint_configurations_json_objects"),
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'active', 'retired', 'blocked')",
            name=op.f("ck_acquisition_endpoint_configurations_status"),
        ),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["acquisition_adapters.id"],
            name=op.f("fk_acquisition_endpoint_configurations_adapter_id_acquisition_adapters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_endpoint_id"],
            ["source_endpoints.id"],
            name=op.f("fk_acquisition_endpoint_configurations_source_endpoint_id_source_endpoints"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_endpoint_configurations")),
        sa.UniqueConstraint(
            "public_id", name=op.f("uq_acquisition_endpoint_configurations_public_id")
        ),
        sa.UniqueConstraint(
            "source_endpoint_id",
            "configuration_version",
            name="uq_acquisition_endpoint_configurations_endpoint_version",
        ),
    )
    op.create_index(
        "uq_acquisition_endpoint_configurations_active_endpoint",
        "acquisition_endpoint_configurations",
        ["source_endpoint_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "acquisition_rate_limit_bindings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("policy_id", sa.BigInteger(), nullable=False),
        sa.Column("scope", sa.String(length=30), nullable=False),
        sa.Column("scope_identity", sa.String(length=512), nullable=False),
        sa.Column("adapter_id", sa.BigInteger(), nullable=True),
        sa.Column("platform", sa.String(length=50), nullable=True),
        sa.Column("secret_reference_id", sa.BigInteger(), nullable=True),
        sa.Column("origin", sa.String(length=512), nullable=True),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("source_endpoint_id", sa.BigInteger(), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'installation' AND adapter_id IS NULL AND platform IS NULL AND secret_reference_id IS NULL AND origin IS NULL AND source_id IS NULL AND source_endpoint_id IS NULL) OR (scope = 'adapter' AND adapter_id IS NOT NULL AND platform IS NULL AND secret_reference_id IS NULL AND origin IS NULL AND source_id IS NULL AND source_endpoint_id IS NULL) OR (scope = 'platform' AND adapter_id IS NULL AND platform IS NOT NULL AND secret_reference_id IS NULL AND origin IS NULL AND source_id IS NULL AND source_endpoint_id IS NULL) OR (scope = 'credential' AND adapter_id IS NULL AND platform IS NULL AND secret_reference_id IS NOT NULL AND origin IS NULL AND source_id IS NULL AND source_endpoint_id IS NULL) OR (scope = 'origin' AND adapter_id IS NULL AND platform IS NULL AND secret_reference_id IS NULL AND origin IS NOT NULL AND source_id IS NULL AND source_endpoint_id IS NULL) OR (scope = 'source' AND adapter_id IS NULL AND platform IS NULL AND secret_reference_id IS NULL AND origin IS NULL AND source_id IS NOT NULL AND source_endpoint_id IS NULL) OR (scope = 'endpoint' AND adapter_id IS NULL AND platform IS NULL AND secret_reference_id IS NULL AND origin IS NULL AND source_id IS NULL AND source_endpoint_id IS NOT NULL)",
            name=op.f("ck_acquisition_rate_limit_bindings_exact_scope"),
        ),
        sa.CheckConstraint(
            "btrim(actor) <> '' AND btrim(reason) <> ''",
            name=op.f("ck_acquisition_rate_limit_bindings_audit_nonempty"),
        ),
        sa.CheckConstraint(
            "scope IN ('installation', 'adapter', 'platform', 'credential', 'origin', 'source', 'endpoint')",
            name=op.f("ck_acquisition_rate_limit_bindings_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["acquisition_adapters.id"],
            name=op.f("fk_acquisition_rate_limit_bindings_adapter_id_acquisition_adapters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["platform"],
            ["platforms.slug"],
            name=op.f("fk_acquisition_rate_limit_bindings_platform_platforms"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["acquisition_rate_limit_policies.id"],
            name=op.f(
                "fk_acquisition_rate_limit_bindings_policy_id_acquisition_rate_limit_policies"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["secret_reference_id"],
            ["secret_references.id"],
            name=op.f("fk_acquisition_rate_limit_bindings_secret_reference_id_secret_references"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_endpoint_id"],
            ["source_endpoints.id"],
            name=op.f("fk_acquisition_rate_limit_bindings_source_endpoint_id_source_endpoints"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_acquisition_rate_limit_bindings_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_rate_limit_bindings")),
        sa.UniqueConstraint("public_id", name=op.f("uq_acquisition_rate_limit_bindings_public_id")),
    )
    op.create_index(
        "uq_acquisition_rate_limit_bindings_active_identity",
        "acquisition_rate_limit_bindings",
        ["scope", "scope_identity"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "acquisition_secret_bindings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("secret_reference_id", sa.BigInteger(), nullable=False),
        sa.Column("adapter_id", sa.BigInteger(), nullable=False),
        sa.Column("adapter_secret_slot_id", sa.BigInteger(), nullable=False),
        sa.Column("authentication_type", sa.String(length=50), nullable=False),
        sa.Column("scope", sa.String(length=30), nullable=False),
        sa.Column("source_endpoint_id", sa.BigInteger(), nullable=True),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("platform_account_id", sa.BigInteger(), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'endpoint' AND source_endpoint_id IS NOT NULL AND source_id IS NULL AND platform_account_id IS NULL) OR (scope = 'source' AND source_endpoint_id IS NULL AND source_id IS NOT NULL AND platform_account_id IS NULL) OR (scope = 'platform_account' AND source_endpoint_id IS NULL AND source_id IS NULL AND platform_account_id IS NOT NULL) OR (scope = 'installation' AND source_endpoint_id IS NULL AND source_id IS NULL AND platform_account_id IS NULL)",
            name=op.f("ck_acquisition_secret_bindings_exact_scope"),
        ),
        sa.CheckConstraint(
            "authentication_type IN ('none', 'bearer_token', 'api_key_header', 'api_key_query', 'basic_auth', 'oauth2_client_credentials', 'cookie_session', 'ssh_key', 'custom')",
            name=op.f("ck_acquisition_secret_bindings_authentication_type"),
        ),
        sa.CheckConstraint(
            "btrim(actor) <> '' AND btrim(reason) <> ''",
            name=op.f("ck_acquisition_secret_bindings_audit_nonempty"),
        ),
        sa.CheckConstraint(
            "scope IN ('endpoint', 'source', 'platform_account', 'installation')",
            name=op.f("ck_acquisition_secret_bindings_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["acquisition_adapters.id"],
            name=op.f("fk_acquisition_secret_bindings_adapter_id_acquisition_adapters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["adapter_secret_slot_id"],
            ["acquisition_adapter_secret_slots.id"],
            name=op.f(
                "fk_acquisition_secret_bindings_adapter_secret_slot_id_acquisition_adapter_secret_slots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["platform_account_id"],
            ["acquisition_platform_accounts.id"],
            name=op.f(
                "fk_acquisition_secret_bindings_platform_account_id_acquisition_platform_accounts"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["secret_reference_id"],
            ["secret_references.id"],
            name=op.f("fk_acquisition_secret_bindings_secret_reference_id_secret_references"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_endpoint_id"],
            ["source_endpoints.id"],
            name=op.f("fk_acquisition_secret_bindings_source_endpoint_id_source_endpoints"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_acquisition_secret_bindings_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_secret_bindings")),
        sa.UniqueConstraint("public_id", name=op.f("uq_acquisition_secret_bindings_public_id")),
    )
    op.create_index(
        "uq_acquisition_secret_bindings_active_endpoint",
        "acquisition_secret_bindings",
        ["adapter_secret_slot_id", "source_endpoint_id"],
        unique=True,
        postgresql_where=sa.text("scope = 'endpoint' AND valid_to IS NULL"),
    )
    op.create_index(
        "uq_acquisition_secret_bindings_active_installation",
        "acquisition_secret_bindings",
        ["adapter_secret_slot_id"],
        unique=True,
        postgresql_where=sa.text("scope = 'installation' AND valid_to IS NULL"),
    )
    op.create_index(
        "uq_acquisition_secret_bindings_active_platform",
        "acquisition_secret_bindings",
        ["adapter_secret_slot_id", "platform_account_id"],
        unique=True,
        postgresql_where=sa.text("scope = 'platform_account' AND valid_to IS NULL"),
    )
    op.create_index(
        "uq_acquisition_secret_bindings_active_source",
        "acquisition_secret_bindings",
        ["adapter_secret_slot_id", "source_id"],
        unique=True,
        postgresql_where=sa.text("scope = 'source' AND valid_to IS NULL"),
    )
    op.create_table(
        "acquisition_leases",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("source_endpoint_id", sa.BigInteger(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("endpoint_configuration_id", sa.BigInteger(), nullable=False),
        sa.Column("execution_identity", sa.String(length=255), nullable=False),
        sa.Column("configuration_version", sa.String(length=100), nullable=False),
        sa.Column("owner_identifier", sa.String(length=255), nullable=False),
        sa.Column(
            "lease_token", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "heartbeat_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("takeover_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(execution_identity) <> '' AND btrim(configuration_version) <> '' AND btrim(owner_identifier) <> ''",
            name=op.f("ck_acquisition_leases_identifiers_nonempty"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'released', 'expired', 'failed')",
            name=op.f("ck_acquisition_leases_status"),
        ),
        sa.CheckConstraint(
            "expires_at > acquired_at AND heartbeat_at >= acquired_at",
            name=op.f("ck_acquisition_leases_time_order"),
        ),
        sa.CheckConstraint(
            "takeover_count >= 0", name=op.f("ck_acquisition_leases_takeover_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_configuration_id"],
            ["acquisition_endpoint_configurations.id"],
            name=op.f(
                "fk_acquisition_leases_endpoint_configuration_id_acquisition_endpoint_configurations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_acquisition_leases_ingestion_run_id_ingestion_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_endpoint_id"],
            ["source_endpoints.id"],
            name=op.f("fk_acquisition_leases_source_endpoint_id_source_endpoints"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_leases")),
        sa.UniqueConstraint("lease_token", name=op.f("uq_acquisition_leases_lease_token")),
        sa.UniqueConstraint("public_id", name=op.f("uq_acquisition_leases_public_id")),
        sa.UniqueConstraint(
            "source_endpoint_id",
            "execution_identity",
            name="uq_acquisition_leases_endpoint_execution",
        ),
    )
    op.create_index(
        "ix_acquisition_leases_expiry", "acquisition_leases", ["status", "expires_at"], unique=False
    )
    op.create_index(
        "uq_acquisition_leases_active_endpoint",
        "acquisition_leases",
        ["source_endpoint_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "acquisition_rate_limit_buckets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("binding_id", sa.BigInteger(), nullable=False),
        sa.Column("secret_reference_id", sa.BigInteger(), nullable=True),
        sa.Column("scope_identity", sa.String(length=512), nullable=False),
        sa.Column(
            "window_started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("request_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "daily_window_started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("daily_request_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("active_concurrency", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_request_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_eligible_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "secret_reference_id IS NULL OR btrim(scope_identity) <> ''",
            name=op.f("ck_acquisition_rate_limit_buckets_credential_identity"),
        ),
        sa.CheckConstraint(
            "request_count >= 0 AND daily_request_count >= 0 AND active_concurrency >= 0",
            name=op.f("ck_acquisition_rate_limit_buckets_counters_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["binding_id"],
            ["acquisition_rate_limit_bindings.id"],
            name=op.f(
                "fk_acquisition_rate_limit_buckets_binding_id_acquisition_rate_limit_bindings"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["secret_reference_id"],
            ["secret_references.id"],
            name=op.f("fk_acquisition_rate_limit_buckets_secret_reference_id_secret_references"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_rate_limit_buckets")),
        sa.UniqueConstraint("binding_id", name="uq_acquisition_rate_limit_buckets_binding"),
    )
    op.create_index(
        "ix_acquisition_rate_limit_buckets_next_eligible",
        "acquisition_rate_limit_buckets",
        ["next_eligible_at"],
        unique=False,
    )
    op.create_table(
        "acquisition_rate_limit_reservations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=False),
        sa.Column("request_identity", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column(
            "reserved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("controlling_binding_id", sa.BigInteger(), nullable=True),
        sa.Column("next_eligible_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(request_identity) <> ''",
            name=op.f("ck_acquisition_rate_limit_reservations_identity_nonempty"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'expired', 'failed')",
            name=op.f("ck_acquisition_rate_limit_reservations_status"),
        ),
        sa.CheckConstraint(
            "expires_at > reserved_at",
            name=op.f("ck_acquisition_rate_limit_reservations_expiry_after_reservation"),
        ),
        sa.ForeignKeyConstraint(
            ["controlling_binding_id"],
            ["acquisition_rate_limit_bindings.id"],
            name=op.f(
                "fk_acquisition_rate_limit_reservations_controlling_binding_id_acquisition_rate_limit_bindings"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_acquisition_rate_limit_reservations_ingestion_run_id_ingestion_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_rate_limit_reservations")),
        sa.UniqueConstraint(
            "ingestion_run_id",
            "request_identity",
            name="uq_acquisition_rate_limit_reservations_run_request",
        ),
        sa.UniqueConstraint(
            "public_id", name=op.f("uq_acquisition_rate_limit_reservations_public_id")
        ),
    )
    op.create_index(
        "ix_acquisition_rate_limit_reservations_expiry",
        "acquisition_rate_limit_reservations",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "acquisition_secret_binding_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("binding_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(actor) <> '' AND btrim(reason) <> ''",
            name=op.f("ck_acquisition_secret_binding_events_audit_nonempty"),
        ),
        sa.CheckConstraint(
            "event_type IN ('created', 'replaced', 'revoked')",
            name=op.f("ck_acquisition_secret_binding_events_event_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(details) = 'object'",
            name=op.f("ck_acquisition_secret_binding_events_details_object"),
        ),
        sa.ForeignKeyConstraint(
            ["binding_id"],
            ["acquisition_secret_bindings.id"],
            name=op.f(
                "fk_acquisition_secret_binding_events_binding_id_acquisition_secret_bindings"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_secret_binding_events")),
    )
    op.create_table(
        "acquisition_lease_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("lease_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("owner_identifier", sa.String(length=255), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(owner_identifier) <> ''", name=op.f("ck_acquisition_lease_events_owner_nonempty")
        ),
        sa.CheckConstraint(
            "event_type IN ('acquired', 'heartbeat', 'taken_over', 'released', 'expired', 'failed', 'replayed')",
            name=op.f("ck_acquisition_lease_events_event_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(details) = 'object'",
            name=op.f("ck_acquisition_lease_events_details_object"),
        ),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["acquisition_leases.id"],
            name=op.f("fk_acquisition_lease_events_lease_id_acquisition_leases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_lease_events")),
    )
    op.create_index(
        "ix_acquisition_lease_events_lease_recorded",
        "acquisition_lease_events",
        ["lease_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "acquisition_rate_limit_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("bucket_id", sa.BigInteger(), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("observation_type", sa.String(length=30), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("retry_after_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_remaining", sa.Integer(), nullable=True),
        sa.Column("provider_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence) = 'object'",
            name=op.f("ck_acquisition_rate_limit_observations_evidence_object"),
        ),
        sa.CheckConstraint(
            "observation_type IN ('http_status', 'retry_after', 'provider_quota', 'provider_reset', 'robots')",
            name=op.f("ck_acquisition_rate_limit_observations_observation_type"),
        ),
        sa.CheckConstraint(
            "http_status IS NULL OR http_status BETWEEN 100 AND 599",
            name=op.f("ck_acquisition_rate_limit_observations_http_status"),
        ),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["acquisition_rate_limit_buckets.id"],
            name=op.f(
                "fk_acquisition_rate_limit_observations_bucket_id_acquisition_rate_limit_buckets"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_acquisition_rate_limit_observations_ingestion_run_id_ingestion_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_rate_limit_observations")),
    )
    op.create_index(
        "ix_acquisition_rate_limit_observations_bucket_recorded",
        "acquisition_rate_limit_observations",
        ["bucket_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "acquisition_rate_limit_reservation_buckets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("reservation_id", sa.BigInteger(), nullable=False),
        sa.Column("bucket_id", sa.BigInteger(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["acquisition_rate_limit_buckets.id"],
            name=op.f(
                "fk_acquisition_rate_limit_reservation_buckets_bucket_id_acquisition_rate_limit_buckets"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["acquisition_rate_limit_reservations.id"],
            name=op.f(
                "fk_acquisition_rate_limit_reservation_buckets_reservation_id_acquisition_rate_limit_reservations"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acquisition_rate_limit_reservation_buckets")),
        sa.UniqueConstraint(
            "reservation_id", "bucket_id", name="uq_rate_reservation_buckets_reservation_bucket"
        ),
    )

    op.execute(
        sa.text(
            """
            CREATE FUNCTION validate_acquisition_endpoint_configuration()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                endpoint_row source_endpoints%ROWTYPE;
                adapter_status text;
            BEGIN
                SELECT * INTO STRICT endpoint_row
                FROM source_endpoints
                WHERE id = NEW.source_endpoint_id;

                SELECT status INTO STRICT adapter_status
                FROM acquisition_adapters
                WHERE id = NEW.adapter_id;

                IF NEW.status = 'active' AND adapter_status <> 'active' THEN
                    RAISE EXCEPTION
                        'Active endpoint configuration requires an active adapter';
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM acquisition_adapter_compatibilities compatibility
                    WHERE compatibility.adapter_id = NEW.adapter_id
                      AND compatibility.endpoint_type = endpoint_row.endpoint_type
                      AND compatibility.endpoint_format = endpoint_row.endpoint_format
                      AND compatibility.acquisition_method = endpoint_row.acquisition_method
                      AND compatibility.platform_key =
                          COALESCE(endpoint_row.platform, '*')
                      AND compatibility.is_active
                ) THEN
                    RAISE EXCEPTION
                        'Endpoint tuple is not registered for the selected adapter';
                END IF;

                IF jsonb_path_exists(
                    NEW.configuration,
                    '$.** ? (@.type() == "object").keyvalue() '
                    '? (@.key like_regex '
                    '"(?i)^(password|secret|token|api[_-]?key|authorization|cookie)$")'
                ) THEN
                    RAISE EXCEPTION
                        'Endpoint configuration contains a forbidden secret-bearing key';
                END IF;

                IF NEW.valid_to IS NOT NULL AND NEW.valid_to <= NEW.valid_from THEN
                    RAISE EXCEPTION
                        'Endpoint configuration validity interval is invalid';
                END IF;
                RETURN NEW;
            END
            $$;

            CREATE TRIGGER trg_validate_acquisition_endpoint_configuration
            BEFORE INSERT OR UPDATE ON acquisition_endpoint_configurations
            FOR EACH ROW
            EXECUTE FUNCTION validate_acquisition_endpoint_configuration();

            CREATE FUNCTION validate_acquisition_secret_binding()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                slot_adapter_id bigint;
                slot_authentication_types varchar[];
                slot_permitted_scopes varchar[];
                reference_state text;
            BEGIN
                SELECT adapter_id, authentication_types, permitted_scopes
                INTO STRICT
                    slot_adapter_id,
                    slot_authentication_types,
                    slot_permitted_scopes
                FROM acquisition_adapter_secret_slots
                WHERE id = NEW.adapter_secret_slot_id
                  AND is_active;

                IF slot_adapter_id <> NEW.adapter_id THEN
                    RAISE EXCEPTION
                        'Secret slot does not belong to the selected adapter';
                END IF;
                IF NOT NEW.authentication_type = ANY(slot_authentication_types) THEN
                    RAISE EXCEPTION
                        'Authentication type is not permitted by the adapter slot';
                END IF;
                IF NOT NEW.scope = ANY(slot_permitted_scopes) THEN
                    RAISE EXCEPTION
                        'Binding scope is not permitted by the adapter slot';
                END IF;

                SELECT state INTO STRICT reference_state
                FROM secret_references
                WHERE id = NEW.secret_reference_id;
                IF reference_state IN ('expired', 'disabled') THEN
                    RAISE EXCEPTION
                        'Expired or disabled secret reference cannot receive a binding';
                END IF;

                IF NEW.valid_to IS NOT NULL AND NEW.valid_to <= NEW.valid_from THEN
                    RAISE EXCEPTION 'Secret binding validity interval is invalid';
                END IF;
                RETURN NEW;
            END
            $$;

            CREATE TRIGGER trg_validate_acquisition_secret_binding
            BEFORE INSERT OR UPDATE ON acquisition_secret_bindings
            FOR EACH ROW
            EXECUTE FUNCTION validate_acquisition_secret_binding();

            CREATE FUNCTION validate_acquisition_rate_binding()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                expected_identity text;
            BEGIN
                expected_identity := CASE NEW.scope
                    WHEN 'installation' THEN 'installation'
                    WHEN 'adapter' THEN 'adapter:' || NEW.adapter_id::text
                    WHEN 'platform' THEN 'platform:' || NEW.platform
                    WHEN 'credential' THEN
                        'credential:' || NEW.secret_reference_id::text
                    WHEN 'origin' THEN 'origin:' || lower(NEW.origin)
                    WHEN 'source' THEN 'source:' || NEW.source_id::text
                    WHEN 'endpoint' THEN
                        'endpoint:' || NEW.source_endpoint_id::text
                END;
                IF NEW.scope_identity <> expected_identity THEN
                    RAISE EXCEPTION
                        'Rate binding scope identity does not match its exact target';
                END IF;
                IF NEW.valid_to IS NOT NULL AND NEW.valid_to <= NEW.valid_from THEN
                    RAISE EXCEPTION 'Rate binding validity interval is invalid';
                END IF;
                RETURN NEW;
            END
            $$;

            CREATE TRIGGER trg_validate_acquisition_rate_binding
            BEFORE INSERT OR UPDATE ON acquisition_rate_limit_bindings
            FOR EACH ROW
            EXECUTE FUNCTION validate_acquisition_rate_binding();

            CREATE FUNCTION validate_acquisition_rate_bucket()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                binding_scope text;
                binding_identity text;
                binding_secret_reference_id bigint;
            BEGIN
                SELECT scope, scope_identity, secret_reference_id
                INTO STRICT
                    binding_scope,
                    binding_identity,
                    binding_secret_reference_id
                FROM acquisition_rate_limit_bindings
                WHERE id = NEW.binding_id
                  AND valid_to IS NULL;

                IF NEW.scope_identity <> binding_identity THEN
                    RAISE EXCEPTION
                        'Rate bucket identity does not match its active binding';
                END IF;
                IF binding_scope = 'credential' THEN
                    IF NEW.secret_reference_id IS DISTINCT FROM
                       binding_secret_reference_id THEN
                        RAISE EXCEPTION
                            'Credential bucket must reference its exact secret identity';
                    END IF;
                ELSIF NEW.secret_reference_id IS NOT NULL THEN
                    RAISE EXCEPTION
                        'Non-credential bucket cannot reference a secret identity';
                END IF;
                RETURN NEW;
            END
            $$;

            CREATE TRIGGER trg_validate_acquisition_rate_bucket
            BEFORE INSERT OR UPDATE ON acquisition_rate_limit_buckets
            FOR EACH ROW
            EXECUTE FUNCTION validate_acquisition_rate_bucket();

            CREATE FUNCTION validate_acquisition_lease()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                configuration_endpoint_id bigint;
                stored_configuration_version text;
                configuration_status text;
            BEGIN
                SELECT source_endpoint_id, configuration_version, status
                INTO STRICT
                    configuration_endpoint_id,
                    stored_configuration_version,
                    configuration_status
                FROM acquisition_endpoint_configurations
                WHERE id = NEW.endpoint_configuration_id;

                IF configuration_endpoint_id <> NEW.source_endpoint_id
                   OR stored_configuration_version <> NEW.configuration_version
                   OR configuration_status <> 'active' THEN
                    RAISE EXCEPTION
                        'Lease requires the exact active endpoint configuration';
                END IF;
                IF NEW.ingestion_run_id IS NOT NULL AND NOT EXISTS (
                    SELECT 1
                    FROM ingestion_runs run
                    WHERE run.id = NEW.ingestion_run_id
                      AND run.source_endpoint_id = NEW.source_endpoint_id
                ) THEN
                    RAISE EXCEPTION
                        'Lease IngestionRun belongs to a different endpoint';
                END IF;
                RETURN NEW;
            END
            $$;

            CREATE TRIGGER trg_validate_acquisition_lease
            BEFORE INSERT OR UPDATE ON acquisition_leases
            FOR EACH ROW
            EXECUTE FUNCTION validate_acquisition_lease();

            CREATE FUNCTION prevent_acquisition_append_only_mutation()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
            END
            $$;

            CREATE TRIGGER trg_secret_reference_events_append_only
            BEFORE UPDATE OR DELETE ON secret_reference_events
            FOR EACH ROW
            EXECUTE FUNCTION prevent_acquisition_append_only_mutation();

            CREATE TRIGGER trg_secret_binding_events_append_only
            BEFORE UPDATE OR DELETE ON acquisition_secret_binding_events
            FOR EACH ROW
            EXECUTE FUNCTION prevent_acquisition_append_only_mutation();

            CREATE TRIGGER trg_lease_events_append_only
            BEFORE UPDATE OR DELETE ON acquisition_lease_events
            FOR EACH ROW
            EXECUTE FUNCTION prevent_acquisition_append_only_mutation();

            CREATE TRIGGER trg_rate_observations_append_only
            BEFORE UPDATE OR DELETE ON acquisition_rate_limit_observations
            FOR EACH ROW
            EXECUTE FUNCTION prevent_acquisition_append_only_mutation();
            """
        )
    )

    op.execute(
        sa.text(
            """
            WITH policy AS (
                INSERT INTO acquisition_rate_limit_policies (
                    slug,
                    version,
                    mode,
                    requests_per_period,
                    period_seconds,
                    burst_size,
                    max_concurrency,
                    minimum_request_spacing_seconds,
                    poll_interval_seconds,
                    daily_request_budget,
                    retry_base_seconds,
                    retry_max_seconds,
                    retry_jitter_percent,
                    exhaustion_action,
                    actor,
                    reason
                )
                VALUES (
                    'phase3-installation-default',
                    '1',
                    'conservative',
                    6,
                    60,
                    1,
                    1,
                    0,
                    900,
                    NULL,
                    60,
                    86400,
                    20,
                    'delay',
                    'migration:e4f6a8b0c213',
                    'Install frozen Phase 3 conservative defaults'
                )
                RETURNING id
            ),
            binding AS (
                INSERT INTO acquisition_rate_limit_bindings (
                    policy_id,
                    scope,
                    scope_identity,
                    actor,
                    reason
                )
                SELECT
                    policy.id,
                    'installation',
                    'installation',
                    'migration:e4f6a8b0c213',
                    'Bind frozen installation-wide default'
                FROM policy
                RETURNING id
            )
            INSERT INTO acquisition_rate_limit_buckets (
                binding_id,
                scope_identity
            )
            SELECT binding.id, 'installation'
            FROM binding;
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            DO $$
            DECLARE
                owned_state_count bigint;
                seed_is_exact boolean;
            BEGIN
                SELECT
                    (SELECT count(*) FROM acquisition_adapters)
                  + (SELECT count(*) FROM acquisition_platform_accounts)
                  + (SELECT count(*) FROM secret_references)
                  + (SELECT count(*) FROM secret_reference_events)
                  + (SELECT count(*) FROM acquisition_endpoint_configurations)
                  + (SELECT count(*) FROM acquisition_leases)
                  + (SELECT count(*) FROM acquisition_lease_events)
                  + (SELECT count(*) FROM acquisition_secret_bindings)
                  + (SELECT count(*) FROM acquisition_secret_binding_events)
                  + (SELECT count(*) FROM acquisition_rate_limit_reservations)
                  + (SELECT count(*) FROM acquisition_rate_limit_reservation_buckets)
                  + (SELECT count(*) FROM acquisition_rate_limit_observations)
                INTO owned_state_count;

                IF owned_state_count <> 0 THEN
                    RAISE EXCEPTION
                        'Refusing lossless-only Phase 3 acquisition-control '
                        'downgrade: owned state exists';
                END IF;

                SELECT
                    (SELECT count(*) FROM acquisition_rate_limit_policies) = 1
                    AND (SELECT count(*) FROM acquisition_rate_limit_bindings) = 1
                    AND (SELECT count(*) FROM acquisition_rate_limit_buckets) = 1
                    AND EXISTS (
                        SELECT 1
                        FROM acquisition_rate_limit_policies policy
                        JOIN acquisition_rate_limit_bindings binding
                          ON binding.policy_id = policy.id
                        JOIN acquisition_rate_limit_buckets bucket
                          ON bucket.binding_id = binding.id
                        WHERE policy.slug = 'phase3-installation-default'
                          AND policy.version = '1'
                          AND policy.mode = 'conservative'
                          AND policy.requests_per_period = 6
                          AND policy.period_seconds = 60
                          AND policy.burst_size = 1
                          AND policy.max_concurrency = 1
                          AND policy.minimum_request_spacing_seconds = 0
                          AND policy.poll_interval_seconds = 900
                          AND policy.daily_request_budget IS NULL
                          AND policy.retry_base_seconds = 60
                          AND policy.retry_max_seconds = 86400
                          AND policy.retry_jitter_percent = 20
                          AND policy.exhaustion_action = 'delay'
                          AND policy.actor = 'migration:e4f6a8b0c213'
                          AND binding.scope = 'installation'
                          AND binding.scope_identity = 'installation'
                          AND binding.valid_to IS NULL
                          AND binding.actor = 'migration:e4f6a8b0c213'
                          AND bucket.scope_identity = 'installation'
                          AND bucket.secret_reference_id IS NULL
                          AND bucket.request_count = 0
                          AND bucket.daily_request_count = 0
                          AND bucket.active_concurrency = 0
                          AND bucket.last_request_at IS NULL
                          AND bucket.blocked_until IS NULL
                          AND bucket.provider_reset_at IS NULL
                          AND bucket.next_eligible_at IS NULL
                    )
                INTO seed_is_exact;

                IF NOT seed_is_exact THEN
                    RAISE EXCEPTION
                        'Refusing lossless-only Phase 3 acquisition-control '
                        'downgrade: policy state differs from the migration seed';
                END IF;
            END
            $$;

            DELETE FROM acquisition_rate_limit_buckets
            WHERE scope_identity = 'installation';

            DELETE FROM acquisition_rate_limit_bindings
            WHERE scope = 'installation'
              AND scope_identity = 'installation'
              AND actor = 'migration:e4f6a8b0c213';

            DELETE FROM acquisition_rate_limit_policies
            WHERE slug = 'phase3-installation-default'
              AND version = '1'
              AND actor = 'migration:e4f6a8b0c213';
            """
        )
    )
    op.drop_table("acquisition_rate_limit_reservation_buckets")
    op.drop_index(
        "ix_acquisition_rate_limit_observations_bucket_recorded",
        table_name="acquisition_rate_limit_observations",
    )
    op.drop_table("acquisition_rate_limit_observations")
    op.drop_index(
        "ix_acquisition_lease_events_lease_recorded", table_name="acquisition_lease_events"
    )
    op.drop_table("acquisition_lease_events")
    op.drop_table("acquisition_secret_binding_events")
    op.drop_index(
        "ix_acquisition_rate_limit_reservations_expiry",
        table_name="acquisition_rate_limit_reservations",
    )
    op.drop_table("acquisition_rate_limit_reservations")
    op.drop_index(
        "ix_acquisition_rate_limit_buckets_next_eligible",
        table_name="acquisition_rate_limit_buckets",
    )
    op.drop_table("acquisition_rate_limit_buckets")
    op.drop_index(
        "uq_acquisition_leases_active_endpoint",
        table_name="acquisition_leases",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_acquisition_leases_expiry", table_name="acquisition_leases")
    op.drop_table("acquisition_leases")
    op.drop_index(
        "uq_acquisition_secret_bindings_active_source",
        table_name="acquisition_secret_bindings",
        postgresql_where=sa.text("scope = 'source' AND valid_to IS NULL"),
    )
    op.drop_index(
        "uq_acquisition_secret_bindings_active_platform",
        table_name="acquisition_secret_bindings",
        postgresql_where=sa.text("scope = 'platform_account' AND valid_to IS NULL"),
    )
    op.drop_index(
        "uq_acquisition_secret_bindings_active_installation",
        table_name="acquisition_secret_bindings",
        postgresql_where=sa.text("scope = 'installation' AND valid_to IS NULL"),
    )
    op.drop_index(
        "uq_acquisition_secret_bindings_active_endpoint",
        table_name="acquisition_secret_bindings",
        postgresql_where=sa.text("scope = 'endpoint' AND valid_to IS NULL"),
    )
    op.drop_table("acquisition_secret_bindings")
    op.drop_index(
        "uq_acquisition_rate_limit_bindings_active_identity",
        table_name="acquisition_rate_limit_bindings",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_table("acquisition_rate_limit_bindings")
    op.drop_index(
        "uq_acquisition_endpoint_configurations_active_endpoint",
        table_name="acquisition_endpoint_configurations",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("acquisition_endpoint_configurations")
    op.drop_index(
        "ix_secret_reference_events_reference_recorded", table_name="secret_reference_events"
    )
    op.drop_table("secret_reference_events")
    op.drop_table("acquisition_platform_accounts")
    op.drop_table("acquisition_adapter_secret_slots")
    op.drop_table("acquisition_adapter_compatibilities")
    op.drop_table("acquisition_adapter_artifact_capabilities")
    op.drop_table("secret_references")
    op.drop_table("acquisition_rate_limit_policies")
    op.drop_index(
        "uq_acquisition_adapters_active_slug",
        table_name="acquisition_adapters",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("acquisition_adapters")
    op.execute(
        sa.text(
            """
            DROP FUNCTION prevent_acquisition_append_only_mutation();
            DROP FUNCTION validate_acquisition_lease();
            DROP FUNCTION validate_acquisition_rate_bucket();
            DROP FUNCTION validate_acquisition_rate_binding();
            DROP FUNCTION validate_acquisition_secret_binding();
            DROP FUNCTION validate_acquisition_endpoint_configuration();
            """
        )
    )
    # ### end Alembic commands ###
